"""Generate a deterministic verification transcript for the committed SQL assets."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from .catalog import PROJECT_ROOT, QUERIES, TABLES
from .service import DatabaseService


def _stringify(value: Any) -> str:
    return "NULL" if value is None else str(value)


def _format_table(columns: list[str], rows: list[dict[str, Any]]) -> str:
    if not columns:
        return "(no columns)"

    widths = {column: len(column) for column in columns}
    for row in rows:
        for column in columns:
            widths[column] = max(widths[column], len(_stringify(row.get(column))))

    header = " | ".join(column.ljust(widths[column]) for column in columns)
    divider = "-+-".join("-" * widths[column] for column in columns)
    body = [
        " | ".join(_stringify(row.get(column)).ljust(widths[column]) for column in columns)
        for row in rows
    ]
    if not body:
        body = ["(0 rows)"]
    return "\n".join((header, divider, *body))


def generate_output_text() -> str:
    lines: list[str] = [
        "Phase 3 Verification Transcript",
        "This transcript was generated by the local backend runner from the same",
        "MySQL-compatible schema, inserts, and queries committed at the repo root.",
        "Run run.sql in MySQL Workbench or the MySQL CLI to regenerate a native",
        "MySQL output transcript for final submission.",
        "",
    ]

    with DatabaseService.create_in_memory() as service:
        service.create_schema()
        lines.append("== CREATE TABLES ==")
        for table in TABLES:
            lines.append(f"Created table {table.name}.")
        lines.append("")

        lines.append("== DESCRIBE TABLES ==")
        for table in TABLES:
            description = service.describe_table(table.name)
            lines.append(f"[{table.name}]")
            lines.append(
                _format_table(
                    ["column_name", "data_type", "not_null", "primary_key_position"],
                    [
                        {
                            "column_name": column["column_name"],
                            "data_type": column["data_type"],
                            "not_null": column["not_null"],
                            "primary_key_position": column["primary_key_position"],
                        }
                        for column in description["columns"]
                    ],
                )
            )
            lines.append("")

        service.seed_data()
        lines.append("== TABLE CONTENTS ==")
        for table in TABLES:
            payload = service.fetch_rows(table.name, limit=500)
            lines.append(f"[{table.name}] ({payload['total_count']} rows)")
            lines.append(_format_table(payload["columns"], payload["rows"]))
            lines.append("")

        lines.append("== QUERY RESULTS ==")
        for query in QUERIES:
            result = service.run_query(query.key, params=dict(query.sample_params))
            lines.append(f"[{query.title}] ({result['row_count']} rows)")
            lines.append(_format_table(result["columns"], result["rows"]))
            lines.append("")

        service.drop_schema()
        lines.append("== DROP TABLES ==")
        for table_name in (
            "uploaded",
            "enrolled",
            "downloaded_courses",
            "contains",
            "offers",
            "documents",
            "course",
            "university",
            "student",
        ):
            lines.append(f"Dropped table {table_name}.")

    return "\n".join(lines).rstrip() + "\n"


def write_output_file(output_path: Path | None = None) -> Path:
    path = output_path or PROJECT_ROOT / "output.txt"
    path.write_text(generate_output_text(), encoding="utf-8")
    return path
